INSERT INTO local (id, descricao) VALUES (10, 'Setor de Agricultura')
INSERT INTO local (id, descricao) VALUES (11, 'Setor de Educação')
INSERT INTO local (id, descricao) VALUES (12, 'Prefeitura Municipal')
INSERT INTO local (id, descricao) VALUES (13, 'Planejamento de Projetos')
INSERT INTO local (id, descricao) VALUES (14, 'Setor de Implantação')